server:
  port: 8880

spring:
  application:
    name: seongsubean-frontend
  cloud:
    discovery:
      enabled: true

  web:
    resources:
      static-locations: classpath:/static/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

